### ISSUE TITLE
Split with_cmp into with_eq_hash and with_ordering?

### ISSUE THREAD

**Issue by Julian** [hynek/characteristic#23]
Quite often I want to define equality on objects by all or most of the attributes, but ordering by a different, smaller subset. Or, similarly, sometimes I want equality + hashing so that I can use them for set membership, but I don't want ordering, which is often meaningless.

Thoughts?

**Comment by Julian** [comment]
Most of the advantage of the with_* is composing them seemingly? I thought you'd generally want to prefer allowing more composition -- if you have just an argument, you can't say, apply ordering selectively to some thing that exists already.

But I don't care much personally, to me it'd just be nice if there was a way to split them at all without characteristic overriding an `__lt__` that I define.

**Comment by hynek** [comment]
Composition kind of went out of the window when we decided (you were part of that decision at EP ;)) to ditch the idea of separating attribute definition from specifying what to do on them. :-/

So to me it sounds right now like:

1. it’s extra complexity
2. it looks like a breaking change (hence my suggestion of ordering=True)
3. it’s a rather fringy case

Am I missing something?

**Comment by Julian** [comment]
(Don't mind me, I'm just clearing out my own GH `issues` tab on things that'll never be needed... Sorry for the inbox spam y'all.)
