### ISSUE TITLE
characteristic_vars or .from_characteristic_attributes?

### ISSUE THREAD

**Issue by Julian** [hynek/characteristic#25]
So, since we have `.characteristic_attributes`, it's now possible to get the characteristic attributes of a characteristically-defined class. Hooray. But getting their values is very slightly nontrivial.

E.g., a few times I've written:

```
@attributes(
     [...]
)
class Foo(object):
    pass

attributes = {attr.name : getattr(foo_instance) for attr in foo_instance.characteristics}
new_foo = Foo(**attributes)
```

but this is subtly wrong, because you need to actually also call `init_aliaser`, which only possibly shows up once you add a private attribute if you're using the default implementation.

Do you think it's worthwhile adding an API for this? Two ideas for one would be to add `characteristic.characteristic_vars` to replace that dict comprehension, in which case the new way to do this would be `Foo(**characteristic.characteristic_vars(...))`. Alternatively, another idea would be to just add a classmethod to characteristic classes to construct them out of dictionaries produced by characteristic_attributes. Either of these sound like decent ideas to you?

**Comment by hynek** [comment]
Hm, do you need it for anything more than for copy constructors?  Wouldn’t it make more sense to implement `__copy__`/`__deepcopy__`?

**Comment by Julian** [comment]
Not just `__copy__`, although if characteristic wanted to start helping to define `__copy__` that might be nice but it'd require the same solution to do so (I never use copy I guess anyhow.)

It's for serialization / deserialization, where the copy is split, first you want the attributes and values, send it over the wire, and deserialize on the other end.

At some point I may take the small bit that I've got that does that and package it as an extension, so if you don't want this upstream I can just stick it there if you prefer.

**Comment by Julian** [comment]
Another possible gotcha is `exclude_from_init` by the way.

**Comment by tomprince** [comment]
Logging is another possible use, where `exclude_from_repr` not `exclude_from_init` is perhaps an appropriate filter.

**Comment by exarkun** [comment]
Something like `characteristic_vars` would also be useful for the copy-with-modifications case.  `namedtuple` offers `_replace` for this and I was thinking about a `modified(obj, attr=newvalue)` API for characteristic (which would give you a new object like `obj` but with `attr` set to `newvalue` instead).

However, `x = characteristic_vars(); x[attr] = newvalue; Foo(**x)` does the job too.  I might still want something that fits into a single expression, but this API at least gets closer than is possible right now (and, for example, I just wrote a `characteristic_attributes`-based thing and didn't realize it was wrong until I read this issue, so it would be nice to have that pitfall remove somehow).

**Comment by hynek** [comment]
This whole issue seems to point out that there’s a whole world of additional tools in the characteristic namespace that would make sense.

`characteristic.replace()`, `.vars()`, …what else makes sense?  Maybe we should think about that first before we rush to something and paint ourselves into a corner.

This is also the point where I regret not having a standardized place for stored attributes. :-/  I guess I’ll start a `__characteristic__` attribute for this and issues to come?

**Comment by vortec** [comment]
I often need to convert characteristic-enhanced objects to JSON, so while I'm not sure if I could benefit from `replace()`, I'd definitely like to have `to_dict()` or `to_json()`.

**Comment by Julian** [comment]
(Don't mind me, I'm just clearing out my own GH `issues` tab on things that'll never be needed... Sorry for the inbox spam y'all.)
